user_auth/authapp/urls.py
from django.conf.urls import url
from authapp import views

app_name = 'authapp'

urlpatterns = [
        url(r'^register/$',views.register,name='register'),
        url(r'^user_login/$',views.user_login,name='user_login')
]

user_auth/user_auth/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from authapp import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^authapp/',include('authapp.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'special/',views.special,name='special'),
]

user_auth/authapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User)
    
    
    #additional 
    portfolio_site=models.URLField(blank=True)
    profile_pic=models.ImageField(upload_to='profile_pics',blank=True)
    
    def __str__(self):
        return self.user.username

user_auth/authapp/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.contrib.auth.models import User
from authapp.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    
    class Meta():
        model = User
        fields = ('username','email','password')
        
class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')
        

user_auth/authapp/views.py
from django.shortcuts import render
from authapp.forms import UserForm, UserProfileInfoForm

from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate,login,logout

# Create your views here.
def index(request):
    return render(request,'authapp/index.html')

def register(request):
    
    registered = False
    
    if request.method=='POST':
        user_form=UserForm(data=request.POST)
        profile_form=UserProfileInfoForm(data=request.POST)
        
        if user_form.is_valid() and profile_form.is_valid():
            user=user_form.save()
            user.set_password(user.password)
            user.save()
            
            profile=profile_form.save(commit=False)
            profile.user=user
            
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            
            profile.save()
            
            registered = True
        
        else:
            print(user_form.errors,profile_form.errors)
    
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    
    return render(request,'authapp/registration.html',
                          {'user_form':user_form,
                              'profile_form':profile_form,
                                  'registered':registered})

@login_required    
def special(request):
    return HttpResponse("You are logged in")    
    
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))
    
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(username=username,password=password)
        
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            
            else:
                return HttpResponse('Account Not Active')
        
        else:
            print('Someone tried to login and failed!')
            print('Username:{} and password:{}'.format(username,password))
            return HttpResponse('Invalid Login Details')
    else:
        return render(request,'authapp/login.html',{})
        
            
            

user_auth/templates/authapp/base.html
<html>
    <head>
        <meta charset="utf-8">
        <title>Basics!!</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <ul class="nav navbar-nav">
                    <li><a class="navbar-brand" href="{% url 'index'%}">Brand</a></li>
                    <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                    <li><a class="navbar-link" href="{% url 'authapp:register' %}">Registration</a></li>
                
                    {% if user.is_authenticated %}
                    <li><a class='navbar-link' href='{% url 'logout' %}'>Logout</a></li>
                    {% else %}
                        <li><a class="navbar-link" href="{% url 'authapp:user_login' %}">Login</a></li>
                    {% endif %}
                
                </ul>
            </div>
        </nav>
        
        <div class="container">
            {% block body_block %}
            
            {% endblock %}
        </div>
    </body>
</html>

user_auth/templates/authapp/index.html
{% extends "authapp/base.html" %}
{% block body_block %}

<div class="jumbotron">
    <h1>Django Level One</h1>
</div>

{% endblock %}

user_auth/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% block body_block %}

<div class="jumbotron">
    <h1>Plaese Login!</h1>
    <form action="{% url 'authapp:user_login' %}" method="post">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input typr="text" name="username" placeholder="Enter Username">
        
        <label for="password">Password:</label>
        <input type="password" name="password">
        
        <input type="submit" value="Login">
    </form>
</div>
{% endblock %}

user_auth/templates/authapp/registration.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}

{% block body_block %}

<div class="jumbotron">
    {% if registered %}
        <h1>Thank You for registering!!</h1>
    {% else %}
        <h1>Register Here!!</h1>
        <h3>Fill out The Form:</h3>
        
        <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" name="" value="Register">
        </form>
    {% endif %}
</div>
{% endblock %}